name: Deploy to EC2 on Production Push

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Build and Deploy Spring Boot
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/demo-0.0.1-SNAPSHOT.jar"
        target: "/home/${{ secrets.EC2_USER }}/"

    - name: SSH and restart systemd service
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mv /home/ec2-user/demo-0.0.1-SNAPSHOT.jar /home/ec2-user/opt/spring-app/app.jar
          systemctl restart springboot